version: '3'

services: 
    myredis:
        image: 'redis:alpine'
    mypostgres:
        image: 'postgres:alpine'
        environment: 
            - POSTGRES_PASSWORD=1qaz2wsx
            - POSTGRES_DB=myappdb
            - POSTGRES_USER=myappuser
        volumes: 
            - C:/Users/janus/Documents/GitHub/DevOps_UG-public/Laboratorium/postgresdata:/var/lib/postgresql/data
    mybackend:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./mybackend
        volumes: 
            - /opt/app/node_modules
            - C:/Users/janus/Documents/GitHub/DevOps_UG-public/Laboratorium/Lab4/mybackend:/opt/app
        environment: 
            - POSTGRES_PASSWORD=1qaz2wsx
            - POSTGRES_DB=myappdb
            - POSTGRES_USER=myappuser
            - REDIS_HOST=myredis
            - POSTGRES_HOST=mypostgres
        ports: 
            - 5000:4000