version: "3.9"
services: 
 myredis:
  container_name: myredis
  networks:
   - mymulticont
  image: redis:alpine
  volumes:
   - redisdata:/data

 mypostgres:
  container_name: mypostgres
  networks: 
   - mymulticont
  volumes:
   - postgresdata:/var/lib/postgresql/data
  environment: 
   POSTGRES_PASSWORD: 1qaz2wsx
  image: postgres:alpine

 mybackend:
  container_name: mybackend
  networks:
   - mymulticont
  build: .
  ports:
   - 8090:5000
  depends_on:
   - mypostgres
   - myredis
  command: ["./wait-for-postgres.sh", "mypostgres", "node", "index.js"]
  image: januszsch/mybackend:latest



networks:
 mymulticont:
  name: mymulticont

volumes:
 postgresdata:
  name: postgresdata
 redisdata:
  name: redisdata

# docker-compose --project-name przepisy up
# docker-compose --project-name przepisy down
# lub
# docker-compose up
# docker-compose down