apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    component: frontend
    app: my-app

spec:
  containers:
    - name: my-nginx
      image: januszsch/myfrontend-nginx:latest
      ports:
        - containerPort: 80
